package com.tom.bean;

public enum SecpSystemCodeEnum {

    SECP_EXCEPTION, SECP_TIME_OUT_ERR, SECP_HTTP_STS_ERR, SECP_PSWD_REGEX_ERR, SECP_RESPON_EMPTY_ERR,
    SECP_TRNS_REQPARAMS_ERR, SECP_CREATE_JWTOKEM_ERR, SECP_TRNS_RESPARAMS_ERR, SECP_HTTPREQUEST_CREATE_ERR;

}
